services:
  dashboard:
    build: .
    # Mount the current directory to /app so dashboard.db is in the project root
    volumes:
      - .:/app
    # working_dir: /app
    environment:
      - APP_ENV=docker
    env_file:
      - .env.docker 
    stdin_open: true
    tty: true
    command: tail -f /dev/null
    restart: unless-stopped